#Some Special Mathematical Fuctions are....
import math
a=int(input("Enter the Number  :"))
b=math.sqrt(a)
print(f"The Sqaue Root of {a} is {b}")
c=math.exp(a)
print(f"The Expo of a is {c}")
d=math.log(a)
print(d)
e=math.log(a,2)
print(e)
f=math.sin(3.14159265/4)
print(f)
g=math.tan(3.14159265/4)
print(g)
h=math.cos(3.14159265/4)
print(h)
print(math.pi)
print(math.e)